---
prompt_for_commit_message: true

mappings:
  - match: '.config/nvim/snippets'
    link_as_dir: true
  - match: ".*gpg-agent.conf.darwin"
    dest: ~/.gnupg/gpg-agent.conf
    target_os: Darwin
  - match: "Library"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true
  - match: ".config/nixos/configuration.nix"
    dest: /etc/nixos/configuration.nix
    target_os:
      - "Linux"

modules:
  # Multiple runtime version manager
  - repo: https://github.com/asdf-vm/asdf.git
    link: none
    location: ~/.asdf
    pull_only: true
  # FZF
  - repo: https://github.com/junegunn/fzf
    link: none
    location: ~/.config/fzf
    pull_only: true
    hooks:
      after_sync:
        - ./install --xdg --key-bindings --no-zsh --no-fish --no-update-rc --completion
  # OH MY ZSH
  - repository: https://github.com/ohmyzsh/ohmyzsh
    link: none
    location: ~/.oh-my-zsh
    pull_only: true
  - repository: git@github.com:chasinglogic/secrets.git
    name: secrets
  # Pre and post exec commands for bash like ZSH has. Required for atuin.
  - repository: https://github.com/rcaloras/bash-preexec
    link: none
    pull_only: true
  # Eternal shell history
  - repository: https://github.com/atuinsh/atuin
    link: none
    pull_only: true
    hooks:
      after_sync:
        - echo "it works"
        - "if [[ ! -x $(which atuin 2>/dev/null) ]]; then bash ./install.sh; fi"
  - repository: https://github.com/doomemacs/doomemacs.git
    link: none
    pull_only: true
    location: ~/.config/emacs
