---
prompt_for_commit_message: true
always_sync_modules: true
mappings:
  - match: ".*gpg-agent.conf"
    target_os:
      - "Darwin"
  - match: "README.org"
    skip: true

hooks:
  after_link:
    - "[ ! -f $HOME/.gnupg/pubring.kbx ] && $HOME/.local/bin/export_keybase"

modules:
  # My encrypted secret files
  - repo: keybase://private/chasinglogic/secrets
