---
prompt_for_commit_message: true

mappings:
  - match: '.config/nvim/UltiSnips'
    link_as_dir: true
  - match: ".*gpg-agent.conf.darwin"
    dest: ~/.gnupg/gpg-agent.conf
    target_os:
      - "Darwin"
  - match: "Library"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true

modules:
  # Node version manager
  - repo: https://github.com/nvm-sh/nvm
    pull_only: true
    link: none
    location: ~/.nvm
  - repository: git@github.com:chasinglogic/secrets.git
    name: secrets
  # Multiple runtime version manager
  - repo: https://github.com/asdf-vm/asdf.git
    link: none
    location: ~/.asdf
    pull_only: true
  # FZF
  - repo: https://github.com/junegunn/fzf
    link: none
    location: ~/.fzf
    pull_only: true
    hooks:
      after_sync:
        - bash install
  # Make bash-completion work for aliases
  - repo: https://github.com/cykerway/complete-alias.git
    link: none
    pull_only: true
