---
prompt_for_commit_message: true

mappings:
  - match: '.config/nvim/snippets'
    link_as_dir: true
  - match: ".*gpg-agent.conf.darwin"
    dest: ~/.gnupg/gpg-agent.conf
    target_os:
      - "Darwin"
  - match: "Library"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true

modules:
  # Multiple runtime version manager
  - repo: https://github.com/asdf-vm/asdf.git
    link: none
    location: ~/.asdf
    pull_only: true
  # FZF
  - repo: https://github.com/junegunn/fzf
    link: none
    location: ~/.config/fzf
    pull_only: true
    hooks:
      after_sync:
        - ./install --xdg --key-bindings --no-zsh --no-fish --no-update-rc --completion
  # Make bash-completion work for aliases
  - repo: https://github.com/cykerway/complete-alias.git
    link: none
    pull_only: true
  - repository: git@github.com:chasinglogic/secrets.git
    name: secrets
  # Pre and post exec commands for bash like ZSH has. Required for atuin.
  - repository: https://github.com/rcaloras/bash-preexec
    link: none
    pull_only: true
  # Eternal shell history
  - repository: https://github.com/atuinsh/atuin
    link: none
    pull_only: true
    hooks:
      after_sync:
        - "[[ ! -x $(which atuin 2>/dev/null) ]] && bash ./install.sh"

