---
prompt_for_commit_message: true
always_sync_modules: true
mappings:
  - match: ".*gpg-agent.conf.darwin"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true

hooks:
  after_sync:
    - systemctl --user daemon-reload
    - systemctl --user enable mbsync.timer emacs

modules:
  # My encrypted secret files
  - repo: keybase://private/chasinglogic/secrets
  # Tmux plugin manager
  - repo: https://github.com/tmux-plugins/tpm
    pull_only: true
    link: none
    location: ~/.tmux/plugins/tpm
