---
prompt_for_commit_message: true
always_sync_modules: true
mappings:
  - match: ".*gpg-agent.conf.darwin"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true

hooks:
  after_link:
    - |
      if [ ! -d "$HOME/.terminfo" ]; then
          tic -x -o ~/.terminfo ~/.local/share/xterm-24bit.src
      fi
  after_sync:
    - systemctl --user daemon-reload
    - systemctl --user enable mbsync.timer emacs

modules:
  # Tmux plugin manager
  - repo: https://github.com/tmux-plugins/tpm
    pull_only: true
    link: none
    location: ~/.tmux/plugins/tpm
  # Node version manager
  - repo: https://github.com/nvm-sh/nvm
    pull_only: true
    link: none
    location: ~/.nvm
  - repository: git@github.com:chasinglogic/secrets.git
