---
prompt_for_commit_message: true
mappings:
  - match: ".*gpg-agent.conf.darwin"
    dest: ~/.gnupg/gpg-agent.conf
    target_os:
      - "Darwin"
  - match: "Library"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true


modules:
  # Tmux plugin manager
  - repo: https://github.com/tmux-plugins/tpm
    pull_only: true
    link: none
    location: ~/.tmux/plugins/tpm
  # Oh My ZSH
  - repo: https://github.com/ohmyzsh/ohmyzsh
    pull_only: true
    link: none
    location: ~/.oh-my-zsh
  # Node version manager
  - repo: https://github.com/nvm-sh/nvm
    pull_only: true
    link: none
    location: ~/.nvm
  - repository: git@github.com:chasinglogic/secrets.git
    name: secrets
