---
prompt_for_commit_message: true
always_sync_modules: true
mappings:
  - match: ".*gpg-agent.conf.darwin"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true

hooks:
  after_sync:
    # Keep neovim and msgpack up to date.
    - pip3 install --user -U pynvim msgpack

modules:
  # My encrypted secret files
  - repo: keybase://private/chasinglogic/secrets
