code_dirs:
  - ~/Code
  - ~/Work
  - ~/kde/src
  - ~/.config/dfm/profiles

excludes:
  - go/src

includes:
  - go/src/github\.com/chasinglogic
  - go/src/github\.com/mongodb
  - go/src/github\.com/evergreen-ci
